### ISSUE TITLE
No callback execution with SENSOR_DELAY_FASTEST 

### ISSUE THREAD

**Issue by rlueders** [LJaraCastillo/flutter_sensors#3]
It seems that when the interval is set to SENSOR_DELAY_FASTEST in the code below, the callback is never executed. No exceptions, but the callback never executes.  However if the interval is changed to any other value SENSOR_DELAY_UI, SENSOR_DELAY_GAME, etc. the callback executes fine.

 final stream = await SensorManager().sensorUpdates(
        sensorId: Sensors.ACCELEROMETER,
        interval: Sensors.SENSOR_DELAY_FASTEST,
      );
      _streamSubscription = stream.listen((sensorEvent) {
        //sensorEvent.accuracy
        if (shock.record) {
          List<dynamic> temp = <dynamic>[];

          temp.add(sensorEvent.data[0]);
          temp.add(sensorEvent.data[1]);
          temp.add(sensorEvent.data[2]);

          dynamic t = calcTotalAcceleration(temp[0], temp[1], temp[2]);
          temp.add(t);

          shock.recordedData.add(temp);
        }
      })

**Comment by LJaraCastillo** [comment]
Fixed in v.0.1.6. Thanks for the issue report.
